### ISSUE TITLE
nodejs 502 after opening the page

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-node.js#10]
**Describe the bug**

基于镜像AWS开机 直接ip访问  网关502错误

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
Amazon default user is ubuntu or ec2-user
https://pm2.keymetrics.io/docs/usage/startup/#user-permissions

```
pm2 save
It will save the process list with the corresponding environments into the dump file $PM2_HOME/.pm2/dump.pm2.
```

**Comment by qiaofeng1227** [comment]
There are two problems in nodejs.
1. delete /usr/bin/nodeXX in role_preend
2. ubuntu or ec2-user, can't start pm2 by server restart

**Comment by zengxc-1996** [comment]
## aws ubuntu 18.04:
![image](https://user-images.githubusercontent.com/63622990/117267109-84b26080-ae88-11eb-8684-98bf2c1c4a4d.png)
## aws linux2:
![image](https://user-images.githubusercontent.com/63622990/117266595-fd64ed00-ae87-11eb-9eb1-4f417aa5c620.png)
## other(root user):
![image](https://user-images.githubusercontent.com/63622990/117266790-300ee580-ae88-11eb-91f8-b0a47307c9c3.png)

**Comment by qiaofeng1227** [comment]
refer to:https://github.com/Websoft9/role_nodejs/issues/2
